################################################################################
#             _____ _     _       _____           _    
#            |  ___(_)___| |__   |_   _|_ _ _ __ | | __
#            | |_  | / __| '_ \    | |/ _` | '_ \| |/ /
#            |  _| | \__ \ | | |   | | (_| | | | |   < 
#            |_|   |_|___/_| |_|   |_|\__,_|_| |_|_|\_\
#
################################################################################

- id: Fish_1
  alias: "Sunset Turn off Fish light"  
  hide_entity: true
  trigger:
      platform: sun
      event: sunset
  action:
      - service: switch.turn_off
        entity_id: switch.fish_light

- id: Fish_2
  alias: "Sunrise Turn on Fish light"  
  hide_entity: true
  trigger:
      platform: sun
      event: sunrise
  action:
      - service: switch.turn_on
        entity_id: switch.fish_light

################################################################################
#                    _   _                      
#                   | | | | ___  _ __ ___   ___ 
#                   | |_| |/ _ \| '_ ` _ \ / _ \
#                   |  _  | (_) | | | | | |  __/
#                   |_| |_|\___/|_| |_| |_|\___|
#                                               
################################################################################

- id: Home_1
  alias: "Set Vaciton mode"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  trigger:
    platform: state
    entity_id: input_boolean.anyone_home
    to: 'off'
    for:
      hours: 24
      minutes: 00
      seconds: 00
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.pushbullet
      data:
        message: Vacation on.
    - service: homeassistant.turn_on
      entity_id: input_boolean.lockdown_mode

- id: Home_2
  alias: "Turn off Vacation mode"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.anyone_home
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode
    - service: notify.pushbullet
      data:
        message: Vacation off.
    - service: homeassistant.turn_off
      entity_id: input_boolean.lockdown_mode

- id: Home_3
  alias: "Set varible when away"
  hide_entity: true
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.regansiphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.sam_pixel
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.anyone_home

- id: Home_4
  alias: "Set varible when home"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.anyone_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.sam_pixel
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.regansiphone
      from: 'not_home'
      to: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.anyone_home

- id: Home_5
  alias: "Auto Arm house"
  condition:
    condition: state
    entity_id: switch.arm_house
    state: 'off'
  trigger:
    platform: state
    entity_id: input_boolean.anyone_home
    from: "on"
    to: "off"
  action:
    - service: notify.pushbullet
      data:
        message: Home is now armed
    - service: homeassistant.turn_on
      entity_id: switch.arm_house

- id: Home_6
  alias: "Auto Disarm house"
  condition:
    condition: state
    entity_id: switch.arm_house
    state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.anyone_home
    from: "off"
    to: "on"
  action:
    - service: notify.pushbullet
      data:
        message: Home is now disarmed
    - service: homeassistant.turn_off
      entity_id: switch.arm_house
    - service: lock.unlock
      entity_id: lock.frontdoor

- id: Home_7
  alias: "Presence PM"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.arm_house
        state: 'off'
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
      - condition: time
        after: '23:00:00'
      - condition: state
        entity_id: binary_sensor.zone_3
        state: 'on'
        for:
          minutes: 15
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  action:
    - service: notify.pushbullet
      data:
        message: Presence PM
    - service: homeassistant.turn_on
      entity_id: switch.arm_house
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'Motion not detected downstairs. Arming house now.'

- id: Home_8
  alias: "Presence AM"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.arm_house
        state: 'on'
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: notify.pushbullet
      data:
        message: Presence AM
    - service: homeassistant.turn_off
      entity_id: switch.arm_house

- id: Home_9
  alias: "lockdown_automation"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.lockdown_mode
    state: 'on'
  trigger:
    - platform: state
      entity_id: lock.frontdoor
      from: 'locked'
      to: 'unlocked'
    - platform: state
      entity_id: binary_sensor.zone_1
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.zone_2
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.zone_3
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.zone_4
      from: 'on'
      to: 'off'
  action:
    - service: tts.google_say
      entity_id: media_player.home_group
      data:
        message: 'Intruder detected contacting authorities now'
    - service: notify.pushbullet
      data:
        message: Intruder detected

- id: Home_10
  alias: "Pretend to be home on vacation"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    - service: light.turn_on
      entity_id: light.office_light
    - service: light.turn_on
      entity_id: light.bedroom_light
    - service: notify.pushbullet
      data:
        message: Mimic Being home on

- id: Home_11
  alias: "Vacation turn off light"
  hide_entity: true
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  trigger:
    platform: time
    at: '23:47:00'
  action:
    - service: light.turn_off
      entity_id: light.office_light
    - service: light.turn_off
      entity_id: light.bedroom_light
    - service: notify.pushbullet
      data:
        message: Mimic Going to sleep


- id: Home_12
  alias: "Individual unlock front door when presence detected"
  hide_entity: false
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.anyone_home
        state: 'on'
        for:
          minutes: 15
      - condition: time
        after: '09:00:00'
        before: '23:00:00'
  trigger:
    - platform: state
      entity_id: device_tracker.sam_pixel
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.regansiphone
      from: 'not_home'
      to: 'home'
  action:
    - service: notify.pushbullet
      data:
        message: Individual unlock
    - service: lock.unlock
      entity_id: lock.frontdoor

################################################################################
#                 
#                  _   _       _   _  __       
#                 | \ | | ___ | |_(_)/ _|_   _ 
#                 |  \| |/ _ \| __| | |_| | | |
#                 | |\  | (_) | |_| |  _| |_| |
#                 |_| \_|\___/ \__|_|_|  \__, |
#                                        |___/ 
#                 
################################################################################

- id: Notify_1
  alias: "Notify if Front door is open"
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.zone_1
    to: 'off'
    for:
      minutes: 15
  action:
    - service: notify.pushbullet
      data:
        message: Front Door has been open for 15 minutes
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'The front door has been open for 15 minutes.'

- id: Notify_2
  alias: "Notify if sliding door is open"
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.zone_2
    to: 'off'
    for:
      minutes: 15
  action:
    - service: notify.pushbullet
      data:
        message: Sliding Door has been open for 15 minutes
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'The sliding door has been open for 15 minutes.'

- id: Notify_3
  alias: "Notify if front door has not locked"
  hide_entity: true
  trigger:
    platform: state
    entity_id: lock.frontdoor
    to: 'unlocked'
    for:
      minutes: 15
  action:
    - service: notify.pushbullet
      data:
        message: The front door has not been locked for 15 minutes
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'The front door has not been locked for 15 minutes.'


################################################################################
#                        __  __ _          
#                       |  \/  (_)___  ___ 
#                       | |\/| | / __|/ __|
#                       | |  | | \__ \ (__ 
#                       |_|  |_|_|___/\___|
#                                          
################################################################################


################################################################################
#                      ____                            
#                     / ___| __ _ _ __ __ _  __ _  ___ 
#                    | |  _ / _` | '__/ _` |/ _` |/ _ \
#                    | |_| | (_| | | | (_| | (_| |  __/
#                     \____|\__,_|_|  \__,_|\__, |\___|
#                                           |___/      
################################################################################

- id: Garage_1
  alias: "Garage Light-Detection boolean on"
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_light
    above: 20
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.garage_light_boolean

- id: Garage_2
  alias: "Garage Light-Detection boolean off"
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_light
    below: 18
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.garage_light_boolean

- id: Garage_3
  alias: "Garage Light-Detection boolean"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.garage_light_boolean 
    to: 'on'
    for:
      minutes: 15
  action:
    - service: notify.pushbullet
      data:
        message: The garage has been illuminated for 15 minutes
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'The garage has been illuminated for 15 minutes.'

- id: Garage_4
  alias: "Garage Temp"
  hide_entity: false
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_temp
    above: 90
  action:
    - service: notify.pushbullet
      data:
        message: The garage is above 90 degrees.
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'The garage is above 90 degrees.'

################################################################################
#                            _______     __
#                           |_   _\ \   / /
#                             | |  \ \ / / 
#                             | |   \ V /  
#                             |_|    \_/   
#                                          
################################################################################
- id: TV_1
  alias: "Chromecast Auto off - off"
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.living_room
    to: 'off'
    for: 
      minutes: 15
  action:
  - service: homeassistant.turn_off
    entity_id: switch.livingroom_tv
